acme/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views
from .views import *
from .views import DeleteView ,UpdateView
from django.views.generic import TemplateView,View
app_name ="blog"
urlpatterns = [
  
    path('index',views.index, name='index'),
    path('home',views.home, name='home'),
    re_path(r'^show/(?P<id>[0-9]+)/$', views.show,name='show'),   
        
    

    # Cart
    re_path(r'^cart/(?P<id>[0-9]+)/$', views.cart,name='cart'),   
    path('addtocart', AddtoCart.as_view(),name='addtocart'),   
    path('emptycart', views.emptycart,name='emptycart'),
    path('managecart/<int:id>', ManageCart.as_view(),name='managecart'),
    # path('plat-update/<int:id>', PlatUpdate.as_view(),name='plat-update'),
    # path('plat-delete/<int:id>', PlatDelete.as_view(),name='plat-delete'),
    path('profil/order/<int:pk>',CustomerOrderDetail.as_view(),name='customerorderdetail'),
    path('adminorderdetail/<int:pk>',AdminOrderDetail.as_view(),name='adminorderdetail'),
    path('adminorderlist/',AdminOrderList.as_view(),name='adminorderlist'),
    # re_path(r'^adminorderdetail/(?P<pk>[0-9]+)/$', AdminOrderDetail.as_view(),name='adminorderdetail'),


    # CRUD
    path('', views.platform,name='platform'),
    
    re_path(r'^plat-update/(?P<pk>[0-9]+)/$', PlatUpdate.as_view(),name='plat-update'),
    re_path(r'^plat-delete/(?P<pk>[0-9]+)/$', PlatDelete.as_view(),name='plat-delete'),
   
    re_path(r'^checkout/$', CheckoutForm.as_view(),name='checkoutform'),
    re_path(r'^profil/$', CustomerProfil.as_view(),name='customerprofil'),
    # re_path(r'^profil/order/(?P<pk>[0-9]+)$', CustomerOrderDetail.as_view(),name='customerorderdetail'),

    # connnexion et authentification
    re_path(r'^registration/$', CustomerRegistrationForm.as_view(),name='customerregistrationform'),
    re_path(r'^login/$', CustomerLoginForm.as_view(),name='customerloginform'),
    re_path(r'^logout/$', CustomerLogoutForm.as_view(),name='customerlogoutform'),

    # admin pages
    re_path(r'^adminlogin/$', AdminLoginForm.as_view(),name='adminloginform'),
    re_path(r'^adminhome/$', AdminHome.as_view(),name='adminhome'),
    re_path(r'^search/$', SearchForm.as_view(),name='searchform'),
    path("admmin-order-<int:pk>-change", AdminOrderStatusChange.as_view(),name='adminorderstatuschange'),



]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Plat(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique = True)
    description = models.TextField()
    image = models.ImageField(upload_to="plats")
    selling_price = models.PositiveIntegerField()

def __str__(self):
    return self.title


class Customer(models.Model):
    
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    full_name = models.CharField(max_length=200)
    address= models.CharField(max_length=200,null=True,blank =True)
    joined_on = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.full_name



class Admin(models.Model):
    
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    full_name = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    image = models.ImageField(upload_to="admin")

    def __str__(self):
        return self.user.username

class Cart(models.Model):
    customer = models.ForeignKey( Customer , on_delete = models.SET_NULL,null =True,blank=True )
    total = models.PositiveIntegerField(default = 0)
    createdat = models.DateTimeField(auto_now_add = True)

def __str__(self):
    return 'Cart:' + str(self.id)
     

class CartPlat(models.Model):
    cart = models.ForeignKey( Cart ,on_delete = models.CASCADE)
    plat = models.ForeignKey( Plat ,on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    rate = models.PositiveIntegerField()

def __str__(self):
    return 'Cart:' + str(self.cart.id) + 'CartPlat:' +str(self.id)
 
ORDER_STATUS = (
    ("Order Received","Order Received"),
    ("Order processing","Order processing"),
    ("On the way","On the way"),
    ("Order Completed","Order Completed"),
    ("Order Canceled","Order Canceled"),
    
)
    





class Order(models.Model):
    cart =models.OneToOneField(Cart,on_delete = models.CASCADE) 
    ordered_by =models.CharField(max_length=255)
    shipping_address =models.CharField(max_length=255)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null = True,blank = True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50,choices = ORDER_STATUS)
    createdat = models.DateTimeField(auto_now_add = True)

def __str__(self):
    return 'Order:' + str(self.id)

blog/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User,auth
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView,View,DetailView,ListView
from django.views.generic.edit import DeleteView,UpdateView,CreateView,FormView
from .models import *

# from .forms import CreateUserForm
from .forms import PlatForm,CheckoutForm,CustomerRegistrationForm,CustomerLoginForm,AdminLoginForm
from django.db.models import Q



class BlogMixin(object):
    def dispatch(self,request,*args,**kwargs):
        cart_id = request.session.get('cart_id')
        if cart_id:
            cart_obj = Cart.objects.get(id = cart_id)
            if request.user.is_authenticated and request.user.customer:
                cart_obj.customer = request.user.customer
                cart_obj.save()
        return super().dispatch(request,*args,**kwargs)

def index(request):
    return render(request,'index.html')
    pass

def home(request):
	plats = Plat.objects.all()
	return render(request,'home.html',{'plats': plats})


def show(request,id):
    plat = Plat.objects.get(pk=id)
    return render(request,'show.html',{'plat': plat}) 

#  Cart
def cart(request,id):
    # get plat  
    plat_obj = Plat.objects.get(pk =id) 
    # check if cart exists
    cart_id =request.session.get('cart_id',None)
    if cart_id:
        cart_obj = Cart.objects.get(id =cart_id)                   
        this_plat_in_cart = cart_obj.cartplat_set.filter(plat = plat_obj)
        if this_plat_in_cart.exists():
            cartplat = this_plat_in_cart.last()
            cartplat.quantity+=1
            cartplat.subtotal+=plat_obj.selling_price
            cartplat.save()
            cart_obj.total+=plat_obj.selling_price
            cart_obj.save()
        else:
            cartplat = CartPlat.objects.create(cart=cart_obj, plat = plat_obj,rate = plat_obj.selling_price,quantity = 1,subtotal = plat_obj.selling_price)
            cart_obj.total+=plat_obj.selling_price
            cart_obj.save()
    else:
        cart_obj = Cart.objects.create(total = 0)
        request.session['cart_id'] = cart_obj.id 
        cartplat = CartPlat.objects.create(cart =cart_obj,plat = plat_obj,rate = plat_obj.selling_price,quantity =1,subtotal=plat_obj.selling_price)
        cart_obj.total += plat_obj.selling_price
        cart_obj.save()

    return render(request,'cart.html',{"cart_obj":cart_obj}) 



class ManageCart(BlogMixin,View):
    def get(self,request,*args,**kwargs):
        cp_id = self.kwargs["id"]
        data=request.GET.get('action', None)
        print(data,cp_id)
        # get cart plat 
        cp_obj = CartPlat.objects.get(id=cp_id)
        cart_obj = cp_obj.cart
        if data =='inc':
            cp_obj.quantity+=1
            cp_obj.subtotal+=cp_obj.rate
            cp_obj.save()
            cart_obj.total+=cp_obj.rate
            cart_obj.save()
            print("succes")
            
        elif data == 'dcr':
            cp_obj.quantity-=1
            cp_obj.subtotal-=cp_obj.rate
            cp_obj.save()
            cart_obj.total-= cp_obj.rate
            cart_obj.save()
            if cp_obj.quantity ==0:
                    cp_obj.delete()
            print("unsucces")
        elif data =='rmv':
            cart_obj.total-= cp_obj.subtotal
            cart_obj.save()
            cp_obj.delete()
            print("resucces")

        else:
            pass
        return redirect("blog:addtocart")
        # return render(request,'addtocart.html') 

def emptycart(request):
    cart_id =request.session.get('cart_id',None)
    if cart_id:
        cart = Cart.objects.get(id = cart_id)
        cart.cartplat_set.all().delete()
        cart.total = 0
        cart.save()
    return redirect("blog:addtocart")

class AddtoCart(BlogMixin,TemplateView):
    template_name = "addtocart.html"
    """docstring for addtocart"""
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id',None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = None
        context['cart'] = cart
        return context


# CRUD




def platform(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PlatForm(request.POST,request.FILES)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            messages.info(request,'formulaire correct')          
            return redirect('blog:home')
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
        else:
            messages.info(request,'formulaire incorrect')  

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PlatForm()
    return render(request,'adminpages/platform.html',{'form':form}) 



class PlatUpdate(UpdateView):
    model = Plat
    # template_name = "update-plat.html"
    # form_class= PlatForm
    fields = ["title","description","image","selling_price","slug"]
    success_url = reverse_lazy('blog:home')
    
   


class PlatDelete(DeleteView):
    # Template_name ="delete.html"
    model = Plat
    success_url = reverse_lazy('blog:home')
    context_object_name = 'plat '
    # success_url ="/"

 # success_url = reverse_lazy('blog:home')



# Authentification et autorisation

class CustomerRegistrationForm(CreateView):
    template_name = "customerregistrationform.html"
    form_class = CustomerRegistrationForm
    success_url = reverse_lazy("blog:home") 
    def form_valid(self,form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        user = User.objects.create_user(username,email,password)
        form.instance.user = user
        login(self.request,user)
        
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
                next_url =self.request.GET.get('next')
                return next_url
        else:
            return self.success_url


class CustomerLoginForm(FormView):
    template_name = "customerloginform.html"
    form_class = CustomerLoginForm
    success_url = reverse_lazy("blog:home")
    def form_valid(self,form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data.get("password")
        usr = authenticate(username =uname,password = pword)
        if usr is not None and usr.customer:
            login(self.request,usr)
        else:
            return render (self.request,self.template_name,{'form':self.form_class,"error": "invalid credentials"})
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
                next_url =self.request.GET.get('next')
                return next_url
        else:
            return self.success_url


class CustomerLogoutForm(View):
    def get(self,request):
        logout(request)
        return redirect ("blog:home")



class CheckoutForm(BlogMixin,CreateView):
    template_name = "checkoutform.html"
    form_class= CheckoutForm
    success_url = reverse_lazy("blog:home")

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated and request.user.customer:
            pass
        else:
            return redirect ("/blog/login/?next=/blog/checkout/")
        return super().dispatch(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id',None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
        else:
            cart_obj = None
        context['cart'] = cart_obj
        return context

    def form_valid(self,form):
        cart_id = self.request.session.get('cart_id',None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            form.instance.cart = cart_obj
            form.instance.subtotal = cart_obj.total
            form.instance.discount = 0
            form.instance.total = cart_obj.total
            form.instance.order_status = "Order Received"
            del self.request.session['cart_id']
        else:
            return redirect("blog:home")        
        return super().form_valid(form)







class CustomerProfil(BlogMixin,TemplateView):
    template_name = "customerprofil.html"

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated and request.user.customer:
            pass
        else:
            return ("/blog/login/?next=blog/profil/")
        return super().dispatch(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.request.user.customer
        print("cool")
        context['customer'] = customer
        orders = Order.objects.filter(cart__customer = customer).order_by('id')      
        context['orders'] = orders
        return context
 





class CustomerOrderDetail(DetailView):
    template_name = "customerorderdetail.html"
    model = Order
    context_object_name = 'ord_obj'

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated and request.user.customer:
            order_id = self.kwargs['pk']
            order = Order.objects.get(id = order_id)
            if request.user.customer != order.cart.customer:
                return redirect ('Blog:customerprofil')
        else:
            return ("/blog/login/?next=blog/profil/")
        return super().dispatch(request,*args,**kwargs)





#Admin pages

blog/templates/addtocart.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">

{% block title %}cart{% endblock %}

{% block body %}
<div class="container">
<div class="row"> 
  <div class="col-md-8"> 
  <h1 class="text-center">voici votre cart</h1> 
    <p>{{cart.cartplat.quantity}}</p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Sn</th>
      <th scope="col">Plat</th>
      <th scope="col">Rate</th>
      <th scope="col">Quantity</th>
       <th scope="col">Subtotal</th>
        <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for cp in cart.cartplat_set.all %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{cp.plat.title}}</td>
      <td>{{cp.rate}}</td>
      <td>{{cp.quantity}}</td>
      <td>{{cp.subtotal}}</td>
        <td>
         <a href="{% url 'blog:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
         <a href="{% url 'blog:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
         <a href="{% url 'blog:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
         
        </td>

    </tr>
    {% endfor %}
    <tr>
      <th colspan="4" class="text-right">Total</th>
      <th>{{cart.total}}</th>
      {% if cart.cartplat_set.all %}
      <th> 
        <a href="{% url 'blog:emptycart' %}"class="btn btn-info">Empty cart</a>
      </th>
     {% endif %}
          
    </tr>
    {% if cart.cartplat_set.all %}
    <tr>
      <th>
        <a href="{% url 'blog:checkoutform' %}"class="btn btn-secondary">Checkout</a>
      </th>    
    </tr>
    {% endif %}
  </tbody>
</table>
</div>
</div> 
</div>
	
{% endblock %}
		

blog/templates/adminprofil.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<p>voici la page de l'administrateur</p>
</body>
</html>

blog/templates/annexe.html
 <!--    <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <img src="{% static 'img/fond.jpg' %}">
            </div>
            
            <div class="col-6  " >
                <div class="row   mb-3 d-flex justify-content-center" >
                    <h1 class="text-center ">Login</h1>
                </div>
                <div class="row d-flex justify-content-center">
                    <form action="" method="post">
                        {% csrf_token %}

                        <div class="row-md-3  ">
                            <div class="form-group rounded-pill">
                            <input class="form-control-lg rounded-pill" type="text" name="username" placeholder="username">
                            </div>
                            <div class="form-group">
                            <input class="form-control-lg rounded-pill"  type="password" name="password" placeholder="password">
                            </div>
                            <div class="form-group">
                                <input class="form-control-lg rounded-pill mg-8" type="submit" value="Submit">
                            </div>
                            
                    </form> 
                    {% for message in messages %}
                    <P id='messages'>{{message}}</P>
                    {% endfor %}
                    <a href="#" class="text-center mr-5">Mot de passe oublié</a>
                    <a href="{% url 'blog:customerregistrationform'%}">S'inscrire</a>

                     <form >
                            <div class="form-group">
                           
                            <input  class="form-control-lg rounded-pill" type="text" placeholder="Email"> 
                        </div>        
                    </form> 
    
                        
                </div>
            </div>
        </div> 
 -->


 <!-- <div class="col-md-6">
    <p>voici la page de registration</p>
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">

    </form>   

</div> -->






<!-- 
   <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <img src="{% static 'img/fond.jpg' %}">
            </div>
            
            <div class="col-6" >
                <div class="row   mb-3 d-flex justify-content-center" >
                    <h1 class="text-center ">Register</h1>
                </div>
                <div class="row d-flex justify-content-center"> -->

                        <!-- <div class="row-md-3  ">
                            <div class="form-group ">
                                <input class="form-control-lg rounded-pill" type="text" name="username" placeholder="username"> -->
                               <!-- <div class="">
                                   {{ form.username.label}}
                                    {{ form.username }}
                                </div>
                                <div>
                                    {{ form.password.label}}
                                    {{ form.password }}
                                </div>
                                <div>
                                    {{ form.full_name.label}}
                                    {{ form.full_name }}
                                </div>

                                    <div>
                                    {{ form.address.label}}
                                    {{ form.address }}
                                </div>

                                    <div>
                                    {{ form.email.label}}
                                    {{ form.email }}
                                </div>
                                  
                                </div>
                           </div>

                            <div class="form-group">
                                <input class="form-control-lg rounded-pill mg-8" type="submit" value="Submit">
                            </div> -->

 
                             <!--  {{ form.as_p }} -->
                         
                           <!--  <div class="form-group">
                            <input class="form-control-lg rounded-pill"  type="password" name="password" placeholder="password">
                            </div> -->
                          <!--   <div class="form-group">
                                <input class="form-control-lg rounded-pill mg-8" type="submit" value="Submit">
                            </div> -->

                             <!--  {% for message in messages %}
                    <P id='messages'>{{message}}</P>
                    {% endfor %}
                    <a href="{% url 'blog:customerregistrationform'%}">Se connecter</a>
 -->
                    <!-- <form >
                            <div class="form-group">
                           
                            <input  class="form-control-lg rounded-pill" type="text" placeholder="Email"> 
                        </div>        
                    </form> -->

<!-- 


  {% for message in messages %}
                    <P id='messages'>{{message}}</P>
                    {% endfor %}
                    <a href="#" class="text-center mr-5">Mot de passe oublié</a>
                    <a href="{% url 'blog:customerregistrationform'%}">S'inscrire</a>
     -->
     <!--  {% url 'blog:customerorderdetail'ord.id %} -->
<!-- 
class CreateUserForm(UserCreationForm):
    firstname = forms.CharField(label='first name', max_length=100)
    lastname = forms.CharField(label='last name', max_length=100)
    username = forms.CharField(label='username', max_length=100)
    email = forms.EmailField(label='email', max_length=100)
    password1   = forms.CharField(label='password1',widget=forms.PasswordInput, max_length=100)
    password2 = forms.CharField(label='password2',widget=forms.PasswordInput, max_length=100)
class PlatForm(forms.ModelForm):
      class meta:
           model = Plat
           fields=["title","description","image","selling_price","slug"] -->

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,400;0,500;1,300;1,400&display=swap" rel="stylesheet">  
    <title></title>
</head>
<body class="container">
   <style>
    .container{
     font-family: 'Montserrat', sans-serif;
     background-color:lightgray;
    }
  </style>
    <nav class="navbar navbar-expand-sm navbar-light bg-light mb-4" >
   <!--  <nav class="navbar navbar-expand-sm navbar-dark bg-dark"> -->
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarsExample03">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:home'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:addtocart'%}">Cart</a>
            </li>
         

            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:checkoutform'%}">checkoutform</a>
            </li>


          
            {% if request.user.customer %}
            <li class="bg-primary">
            <p> welcome {{ request.user.username}}</p>

             <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:customerprofil'%}">customerprofil</a>
            </li>
           
            </li>
             <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:customerlogoutform'%}">Logout</a>
            </li> 
            {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:customerregistrationform'%}">Inscription</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:customerloginform'%}">Connexion</a>
            </li>
             <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:adminloginform'%}">Adminlogin</a>
            </li>
            {% endif %}            
          </ul>
          <form  action="{% url 'blog:searchform' %}" method = 'GET' class="form-inline my-2 my-md-0">
            <input class="form-control" type="text" name="keyword" placeholder="Search plat here" required>
            <button>search plat</button>
          </form>
        </div>
      </nav>
      {% block content %}
      {% block body %}{% endblock %}
      {% endblock %}
</body>
</html>

blog/templates/cart.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">

{% block title %}home{% endblock %}

{% block body %}
    <h1 class="text-center">add to the cart succesfully</h1>
    {{cart_obj}}

{% endblock %}

blog/templates/customerprofil.html
{% extends "base.html" %}
{% load static %}
<!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
<!-- <link href="/your-path-to-fontawesome/css/all.css" rel="stylesheet"> -->
<link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">

{% block title %}customerprofil{% endblock %}

{% block body %}
<h1 class="text-center m-4">Profil de <strong>{{ request.user.username}} </strong></h1>
<hr>
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h3 class="text-center">Detail informations</h3>
			<hr>
			<p><span class="font-weight-bold">Name : </span>{{customer.full_name}}</p>
			<p><span class="font-weight-bold">Username : </span>{{customer.user.username}}</p>
			<p><span class="font-weight-bold">Email : </span>{{customer.user.email}}</p>
			<p><span class="font-weight-bold">Adress : </span>{{customer.address}}</p>
			<p><span class="font-weight-bold">joined_on : </span>{{customer.joined_on}}</p>
		</div>

		<div class="col-md-8">
			<h3 class="text-center">Previous orders</h3>
			<hr>
			<table class="table">
				<thead>
					<tr>
					<th>SN</th>
					<th>Order</th>
					<th>Amount</th>
					<th>Orderd_on</th>
					<th>Status</th>					
				</tr>					
				</thead>
				<tbody>
					{% for order in orders %}
					<tr>
						<td>{{ forloop.counter }}</td>
						<td ><a href="{% url 'blog:customerorderdetail' order.id %}">#ORDER{{order.id}}</a></td>
						<td>{{order.total}}</td>
						<td>{{order.createdat|timesince}}ago</td>
						<td>{{order.order_status}}</td>
					</tr>
					{% endfor %}
				</tbody>
				
			</table>
			
		</div>
	</div>
</div>
    

   <!--  <a href=""><i class="fas fa-user"></i>le profil</a> -->
  


{% endblock %}

blog/templates/home.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">

{% block title %}home{% endblock %}

{% block body %}  
<div class="container">
     <h1 class="text-center m-4">welcome <strong>{{ request.user.username}} </strong>to UrcaDelima fastfood</h1>
     <hr>
    <div class="row">
        {% for plat in plats %}
        <div class="col-md-3">
            <h3>{{plat.title}}</h3>   
            <img src="{{plat.image.url}}" alt="" width="250" height="200">
            <p>price:Rs.{{plat.selling_price}}</p>
            <p><a href="{% url 'blog:show' plat.id %}">{{plat.description|truncatewords:2}}</a></p>
            <a href="{% url 'blog:cart' plat.id %}" class="btn btn-success">add to cart</a>
            
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}



    

blog/templates/show.html
{% extends "base.html" %}
{% load static %}


{% block title %}show{% endblock %}

{% block body %}

    <h1 class="text-center mb-4"><strong>{{plat.title}}</strong></h1><hr>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img src="{{plat.image.url}}" alt="" width="250" height="200">      
            </div>
            <div class="col-md-8">
                <h3 class="text-center mb-4">{{plat.title}}</h3>
                <p class="btn btn-primary">Price: Rs.{{plat.selling_price}}</p> 
                <p>{{plat.description}}</p>
                <a href="{% url 'blog:cart' plat.id %}" class="btn btn-success">add to cart</a><hr>
                {% if request.user.admin %}
                <a href="{% url 'blog:plat-update' plat.id %}" class="btn btn-warning">Update</a>
                <a href="{% url 'blog:plat-delete' plat.id %}"class="btn btn-danger">Delete</a>
                {% endif %}
                



            </div>
        </div>
    </div>
    
{% endblock %}