acme/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views
from .views import *
from .views import DeleteView ,UpdateView
from django.views.generic import TemplateView,View
app_name ="blog"
urlpatterns = [
  
    path('index',views.index, name='index'),
    path('home',views.home, name='home'),
    re_path(r'^show/(?P<id>[0-9]+)/$', views.show,name='show'),   
        
    

    # Cart
    re_path(r'^cart/(?P<id>[0-9]+)/$', views.cart,name='cart'),   
    path('addtocart', AddtoCart.as_view(),name='addtocart'),   
    path('emptycart', views.emptycart,name='emptycart'),
    path('managecart/<int:id>', ManageCart.as_view(),name='managecart'),
    # path('plat-update/<int:id>', PlatUpdate.as_view(),name='plat-update'),
    # path('plat-delete/<int:id>', PlatDelete.as_view(),name='plat-delete'),
    path('profil/order/<int:pk>',CustomerOrderDetail.as_view(),name='customerorderdetail'),
    path('adminorderdetail/<int:pk>',AdminOrderDetail.as_view(),name='adminorderdetail'),
    path('adminorderlist/',AdminOrderList.as_view(),name='adminorderlist'),
    # re_path(r'^adminorderdetail/(?P<pk>[0-9]+)/$', AdminOrderDetail.as_view(),name='adminorderdetail'),


    # CRUD
    path('', views.platform,name='platform'),
    
    re_path(r'^plat-update/(?P<pk>[0-9]+)/$', PlatUpdate.as_view(),name='plat-update'),
    re_path(r'^plat-delete/(?P<pk>[0-9]+)/$', PlatDelete.as_view(),name='plat-delete'),
   
    re_path(r'^checkout/$', CheckoutForm.as_view(),name='checkoutform'),
    re_path(r'^profil/$', CustomerProfil.as_view(),name='customerprofil'),
    # re_path(r'^profil/order/(?P<pk>[0-9]+)$', CustomerOrderDetail.as_view(),name='customerorderdetail'),

    # connnexion et authentification
    re_path(r'^registration/$', CustomerRegistrationForm.as_view(),name='customerregistrationform'),
    re_path(r'^login/$', CustomerLoginForm.as_view(),name='customerloginform'),
    re_path(r'^logout/$', CustomerLogoutForm.as_view(),name='customerlogoutform'),

    # admin pages
    re_path(r'^adminlogin/$', AdminLoginForm.as_view(),name='adminloginform'),
    re_path(r'^adminhome/$', AdminHome.as_view(),name='adminhome'),
    re_path(r'^search/$', SearchForm.as_view(),name='searchform'),
    path("admmin-order-<int:pk>-change", AdminOrderStatusChange.as_view(),name='adminorderstatuschange'),



]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Plat(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique = True)
    description = models.TextField()
    image = models.ImageField(upload_to="plats")
    selling_price = models.PositiveIntegerField()

def __str__(self):
    return self.title


class Customer(models.Model):
    
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    full_name = models.CharField(max_length=200)
    address= models.CharField(max_length=200,null=True,blank =True)
    joined_on = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.full_name



class Admin(models.Model):
    
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    full_name = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    image = models.ImageField(upload_to="admin")

    def __str__(self):
        return self.user.username

class Cart(models.Model):
    customer = models.ForeignKey( Customer , on_delete = models.SET_NULL,null =True,blank=True )
    total = models.PositiveIntegerField(default = 0)
    createdat = models.DateTimeField(auto_now_add = True)

def __str__(self):
    return 'Cart:' + str(self.id)
     

class CartPlat(models.Model):
    cart = models.ForeignKey( Cart ,on_delete = models.CASCADE)
    plat = models.ForeignKey( Plat ,on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    rate = models.PositiveIntegerField()

def __str__(self):
    return 'Cart:' + str(self.cart.id) + 'CartPlat:' +str(self.id)
 
ORDER_STATUS = (
    ("Order Received","Order Received"),
    ("Order processing","Order processing"),
    ("On the way","On the way"),
    ("Order Completed","Order Completed"),
    ("Order Canceled","Order Canceled"),
    
)
    





class Order(models.Model):
    cart =models.OneToOneField(Cart,on_delete = models.CASCADE) 
    ordered_by =models.CharField(max_length=255)
    shipping_address =models.CharField(max_length=255)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null = True,blank = True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50,choices = ORDER_STATUS)
    createdat = models.DateTimeField(auto_now_add = True)

def __str__(self):
    return 'Order:' + str(self.id)

blog/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User,auth
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView,View,DetailView,ListView
from django.views.generic.edit import DeleteView,UpdateView,CreateView,FormView
from .models import *

# from .forms import CreateUserForm
from .forms import PlatForm,CheckoutForm,CustomerRegistrationForm,CustomerLoginForm,AdminLoginForm
from django.db.models import Q



class BlogMixin(object):
    def dispatch(self,request,*args,**kwargs):
        cart_id = request.session.get('cart_id')
        if cart_id:
            cart_obj = Cart.objects.get(id = cart_id)
            if request.user.is_authenticated and request.user.customer:
                cart_obj.customer = request.user.customer
                cart_obj.save()
        return super().dispatch(request,*args,**kwargs)

def index(request):
    return render(request,'index.html')
    pass

def home(request):
	plats = Plat.objects.all()
	return render(request,'home.html',{'plats': plats})


def show(request,id):
    plat = Plat.objects.get(pk=id)
    return render(request,'show.html',{'plat': plat}) 

#  Cart
def cart(request,id):
    # get plat  
    plat_obj = Plat.objects.get(pk =id) 
    # check if cart exists
    cart_id =request.session.get('cart_id',None)
    if cart_id:
        cart_obj = Cart.objects.get(id =cart_id)                   
        this_plat_in_cart = cart_obj.cartplat_set.filter(plat = plat_obj)
        if this_plat_in_cart.exists():
            cartplat = this_plat_in_cart.last()
            cartplat.quantity+=1
            cartplat.subtotal+=plat_obj.selling_price
            cartplat.save()
            cart_obj.total+=plat_obj.selling_price
            cart_obj.save()
        else:
            cartplat = CartPlat.objects.create(cart=cart_obj, plat = plat_obj,rate = plat_obj.selling_price,quantity = 1,subtotal = plat_obj.selling_price)
            cart_obj.total+=plat_obj.selling_price
            cart_obj.save()
    else:
        cart_obj = Cart.objects.create(total = 0)
        request.session['cart_id'] = cart_obj.id 
        cartplat = CartPlat.objects.create(cart =cart_obj,plat = plat_obj,rate = plat_obj.selling_price,quantity =1,subtotal=plat_obj.selling_price)
        cart_obj.total += plat_obj.selling_price
        cart_obj.save()

    return render(request,'cart.html',{"cart_obj":cart_obj}) 



class ManageCart(BlogMixin,View):
    def get(self,request,*args,**kwargs):
        cp_id = self.kwargs["id"]
        data=request.GET.get('action', None)
        print(data,cp_id)
        # get cart plat 
        cp_obj = CartPlat.objects.get(id=cp_id)
        cart_obj = cp_obj.cart
        if data =='inc':
            cp_obj.quantity+=1
            cp_obj.subtotal+=cp_obj.rate
            cp_obj.save()
            cart_obj.total+=cp_obj.rate
            cart_obj.save()
            print("succes")
            
        elif data == 'dcr':
            cp_obj.quantity-=1
            cp_obj.subtotal-=cp_obj.rate
            cp_obj.save()
            cart_obj.total-= cp_obj.rate
            cart_obj.save()
            if cp_obj.quantity ==0:
                    cp_obj.delete()
            print("unsucces")
        elif data =='rmv':
            cart_obj.total-= cp_obj.subtotal
            cart_obj.save()
            cp_obj.delete()
            print("resucces")

        else:
            pass
        return redirect("blog:addtocart")
        # return render(request,'addtocart.html') 

def emptycart(request):
    cart_id =request.session.get('cart_id',None)
    if cart_id:
        cart = Cart.objects.get(id = cart_id)
        cart.cartplat_set.all().delete()
        cart.total = 0
        cart.save()
    return redirect("blog:addtocart")

class AddtoCart(BlogMixin,TemplateView):
    template_name = "addtocart.html"
    """docstring for addtocart"""
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id',None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = None
        context['cart'] = cart
        return context


# CRUD




def platform(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PlatForm(request.POST,request.FILES)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            messages.info(request,'formulaire correct')          
            return redirect('blog:home')
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
        else:
            messages.info(request,'formulaire incorrect')  

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PlatForm()
    return render(request,'adminpages/platform.html',{'form':form}) 



class PlatUpdate(UpdateView):
    model = Plat
    # template_name = "update-plat.html"
    # form_class= PlatForm
    fields = ["title","description","image","selling_price","slug"]
    success_url = reverse_lazy('blog:home')
    
   


class PlatDelete(DeleteView):
    # Template_name ="delete.html"
    model = Plat
    success_url = reverse_lazy('blog:home')
    context_object_name = 'plat '
    # success_url ="/"

 # success_url = reverse_lazy('blog:home')



# Authentification et autorisation

class CustomerRegistrationForm(CreateView):
    template_name = "customerregistrationform.html"
    form_class = CustomerRegistrationForm
    success_url = reverse_lazy("blog:home") 
    def form_valid(self,form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        user = User.objects.create_user(username,email,password)
        form.instance.user = user
        login(self.request,user)
        
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
                next_url =self.request.GET.get('next')
                return next_url
        else:
            return self.success_url


class CustomerLoginForm(FormView):
    template_name = "customerloginform.html"
    form_class = CustomerLoginForm
    success_url = reverse_lazy("blog:home")
    def form_valid(self,form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data.get("password")
        usr = authenticate(username =uname,password = pword)
        if usr is not None and usr.customer:
            login(self.request,usr)
        else:
            return render (self.request,self.template_name,{'form':self.form_class,"error": "invalid credentials"})
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
                next_url =self.request.GET.get('next')
                return next_url
        else:
            return self.success_url


class CustomerLogoutForm(View):
    def get(self,request):
        logout(request)
        return redirect ("blog:home")



class CheckoutForm(BlogMixin,CreateView):
    template_name = "checkoutform.html"
    form_class= CheckoutForm
    success_url = reverse_lazy("blog:home")

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated and request.user.customer:
            pass
        else:
            return redirect ("/blog/login/?next=/blog/checkout/")
        return super().dispatch(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id',None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
        else:
            cart_obj = None
        context['cart'] = cart_obj
        return context

    def form_valid(self,form):
        cart_id = self.request.session.get('cart_id',None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            form.instance.cart = cart_obj
            form.instance.subtotal = cart_obj.total
            form.instance.discount = 0
            form.instance.total = cart_obj.total
            form.instance.order_status = "Order Received"
            del self.request.session['cart_id']
        else:
            return redirect("blog:home")        
        return super().form_valid(form)







class CustomerProfil(BlogMixin,TemplateView):
    template_name = "customerprofil.html"

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated and request.user.customer:
            pass
        else:
            return ("/blog/login/?next=blog/profil/")
        return super().dispatch(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.request.user.customer
        print("cool")
        context['customer'] = customer
        orders = Order.objects.filter(cart__customer = customer).order_by('id')      
        context['orders'] = orders
        return context
 





class CustomerOrderDetail(DetailView):
    template_name = "customerorderdetail.html"
    model = Order
    context_object_name = 'ord_obj'

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated and request.user.customer:
            order_id = self.kwargs['pk']
            order = Order.objects.get(id = order_id)
            if request.user.customer != order.cart.customer:
                return redirect ('Blog:customerprofil')
        else:
            return ("/blog/login/?next=blog/profil/")
        return super().dispatch(request,*args,**kwargs)





#Admin pages

blog/templates/adminpages/adminhome.html
{% extends "adminpages/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">

{% block title %}home{% endblock %}

{% block body %}
    <div class="container">
	<h1 class="text-center">Admin Home</h1>
	<div class="row">
		<div class="col-md-12">
			<h3 class="text-center">pendings orders</h3>
			<table class="table">
				<thead>
					<tr>
					<th>SN</th>
					<th>Customer</th>
					<th>Order</th>
					<th>Ordered On</th>
					<th>Ammount</th>
				</tr>
				</thead>
				
				<tbody>
					{% for order in pendingorders %}
					<tr>
						<td>{{forloop.counter}}</td>
						<td>{{order.ordered_by}}</td>
						<td ><a href="{% url 'blog:adminorderdetail' order.pk %}">#ORDER{{order.id}}</a></td>
						<td>{{order.createdat}}</td>
						<td>{{order.total}}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
   
</div>
   


{% endblock %}

blog/templates/adminpages/adminloginform.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
 <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,400;0,500;1,300;1,400&display=swap" rel="stylesheet"> 

{% block title %}{% endblock %}

{% block body %}

<style>
    .container-fluid{
     font-family: 'Montserrat', sans-serif;
     background-color:lightgray;
    }
  </style>

 <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'img/fond.jpg' %}">
            </div>
            
            <div class="col-md-6 ">
                <div class="row mb-3 d-flex justify-content-center" >
                    <h1 class="text-center ">Admin Login</h1>
                </div>
                <div class="row d-flex justify-content-center">
                    <form action="" method="post">
                        {% csrf_token %}

                        <div class="row-md-3  ">
                            <div class="form-group rounded-pill">
                                {{ form.username.label}}
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                {{ form.password.label}}
                                {{ form.password }}
                            </div>
                            <div class="form-group">
                                <input class="form-control-lg rounded-pill mg-8" type="submit" value="Submit">
                            </div>
                            
                    </form>                        
                </div>
            </div>
        </div>           
   
</div>
   

{% endblock %}

blog/templates/adminpages/adminorderdetail.html
{% extends "adminpages/base.html" %}
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


{% block title %}home{% endblock %}

{% block body %}
    <div class="container">
		<h1 class="text-center">Admin order detail</h1>
		<div class="row">
			<div class="col-md-8 mx-auto">
					<h3 class="text-center text-info">Order Details</h3><hr>
					<p><span class="font-weight-bold">Order ID: </span>#ORDER_{{ord_obj.id}}</p>
					<p><span class="font-weight-bold">Order Status: </span>{{ord_obj.order_status}}</p>
					<p><span class="font-weight-bold">Order On: </span>{{ord_obj.createdat}} {{ord_obj.createdat|timesince}} ago</p>
					<p><span class="font-weight-bold"> Customer Information:  </span>By {{ord_obj.ordered_by}}</p>
					<p><span class="font-weight-bold">Shipping Adress: </span>{{ord_obj.shipping_address}}</p>
					<p><span class="font-weight-bold">Shipping Information:  </span>{{ord_obj.shipping_address}} {{ord_obj.email}}</p>
					<h4 class="text-center text-warning">Ordered Items</h4>
					<table class="table">
						<thead>
							<tr>
							<th>SN</th>
							<th>Item</th>
							<th>Rate</th>
							<th>Quantity</th>
							<th>subtotal</th>
							</tr>
							
						</thead>
						<tbody>
							{% for cp in ord_obj.cart.cartplat_set.all %}
							<tr>
								<td>{{forloop.counter}}</td>
								<td><a target="_blank" href="{url'blog:show'cp_plat.id}"></a>{{cp.product.title}}{{cp.product.id}}</td>
								<td>{{cp.rate}}</td>
								<td>{{cp.quantity}}</td>
								<td>{{cp.subtotal}}</td>
							</tr>
							{% endfor %}
							<tr>
								<th colspan="4" class="text-right">	Total:</th>
								<th>RS {{ord_obj.total}}</th>
							</tr>
						</tbody>
					</table>
					<form action="{% url 'blog:adminorderstatuschange' ord_obj.id %}" method="POST">
					 {% csrf_token %}
						<select name="status">
							{% for i,j in allstatus %}
							<option value="{{i}}" {% if i == ord_obj.oder_status %} selected {% endif %}>{{j}}</option>
							{% endfor %}							
						</select>
						<button class="btn btn-info">change</button>
					</form>
					
			</div>
		</div>   
	</div>
   

{% endblock %}

blog/templates/adminpages/adminorderlist.html
{% extends "adminpages/base.html" %}
{% load static %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">

{% block title %}Admin order list{% endblock %}

{% block body %}
<div class="container">
	<h1 class="text-center">Admin order list</h1>
	<table class="table">
				<thead>
					<tr>
					<th>SN</th>
					<th>Customer</th>
					<th>Order</th>
					<th>Ordered On</th>
					<th>Ammount</th>
					<th>Status</th>
				</tr>
				</thead>
				
				<tbody>
					{% for order in allorders %}
					<tr>
						<td>{{forloop.counter}}</td>
						<td>{{order.ordered_by}}</td>
						<td ><a href="{% url 'blog:adminorderdetail' order.pk %}">#ORDER{{order.id}}</a></td>
						<td>{{order.createdat}}</td>
						<td>{{order.total}}</td>
						<td>{{order.order_status}}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
</div>
    

    

{% endblock %}

blog/templates/adminpages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,400;0,500;1,300;1,400&display=swap" rel="stylesheet">  
<title>Admin</title>
</head>
<body class="container">
  <style>
    .container{
     font-family: 'Montserrat', sans-serif;
     background-color:lightgray;
    }
  </style>
	<!--  <nav class="navbar navbar-expand-sm navbar-dark bg-dark"> -->
     <nav class="navbar navbar-expand-sm navbar-light bg-light mb-4" >
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarsExample03">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:adminhome' %}">adminhome <span class="sr-only">(current)</span></a>
            </li>
           	<li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:adminorderlist'%}">adminorderlist</a>         
           	</li>
              <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:adminloginform'%}">adminorlogin</a>         
            </li>



             <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:adminhome'%}">adminprofil</a>
            </li>

            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:platform'%}">Add</a>
            </li>
           

           </ul>

        </div>
      </nav>

      {% block content %}
      {% block body %}{% endblock %}
      {% endblock %}
	
</body>
</html>

blog/templates/adminpages/plat-update.html
{% extends "adminpages/base.html" %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
   
{% block title %}home page{% endblock title %}
	
	{% block content %}
	<p>
		are you show you want to delete the plat
	</p>

blog/templates/adminpages/plat_confirm_delete.html
{% extends "adminpages/base.html" %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
   
{% block title %}home page{% endblock title %}
	
	{% block content %}
	<p>
		are you show you want to delete the plat
	</p>



  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Yes, delete."/>
  </form>
		<!-- <h1 class="text-center">Add a plat</h1><hr>
		<div class="col-md-6 mx-auto">
       
		<form action="{% url 'blog:delete' pk=plat.id %}" method="post">		
         {% csrf_token %}
    		<div class="form-group">
                <input class="rounded-pill " type="submit" value="confirm">
    		</div> 
        </div>
        </form>  -->

<!-- 
  <div class="panel-footer">
  <a type="button" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-envelope"></i></a>
    <span class="pull-right">
      <a href="{% url 'blog:update' pk=plat.id %}" type="button" class="btn btn-small btn-info"><i class="glyphicon glyphicon-edit"></i></a>
      <form action="{% url 'blog:delete' pk=plat.id %}" method="post" style="display: inline;">
          {% csrf_token %}
          <input type="hidden" name="plat_id" value="confirm"/>
               <button type="submit" class="btn btn-danger btn-small">
                   <span class="glyphicon glyphicon-trash"></span>
                </button>
        </form>
     </span>
   </div> 




   <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>   -->
{% endblock %}